### ISSUE TITLE
Failed to create Server instance when metadataStatementRepository is not provided since 3.3

### ISSUE THREAD

**Issue by yrccondor** [web-auth/webauthn-framework#173]
**Describe the bug:**
Failed to create Server instance when `metadataStatementRepository` is `null` since version 3.3.

Looks like this change was introduced in 33a39a9 and shipped in 3.3.0, where `setMetadataStatementRepository` required an instance of `MetadataStatementRepository` and `null` is invalid.

**To Reproduce:**
When I call
```php
$server = new Server(
    $rpEntity,
    $credentialSourceRepository,
    null
);
```
I got `Argument 1 passed to Webauthn\Server::setMetadataStatementRepository() must be an instance of Webauthn\MetadataService\MetadataStatementRepository, null given, called in vendor/web-auth/webauthn-lib/src/Server.php on line 145`

**Comment by yrccondor** [comment]
And also:
- `AndroidSafetyNetAttestationStatementSupport::enableApiVerification` doesn't accept `null` arguments since 3.3, which means I must provid things like Google API Key
- `AttestationObjectLoader::setLogger` and `PublicKeyCredentialLoader::setLogger` doesn't accept `null` arguments since 3.3, which means I must provid a logger instance

Does this an intentional change?

**Comment by Spomky** [comment]
Hi @yrccondor,

I confirm this is not the desired behavior.
It is resolved by #170 and will be available soon.

I will close this issue want tagged.
Regards.

**Comment by Spomky** [comment]
Hi,

This should be fixed with v3.3.4.
Can you confirm the error is gone with the latest version?

**Comment by yrccondor** [comment]
Hi,

what does `otherUI` do? Looks like it's webauthn-related.

https://github.com/web-auth/webauthn-framework/blob/3439e8e8ce5bd24dacd2962bcaff61cb4b4d21ac/src/webauthn/src/PublicKeyCredentialSource.php#L81

In https://github.com/web-auth/webauthn-framework/blob/3439e8e8ce5bd24dacd2962bcaff61cb4b4d21ac/src/webauthn/src/PublicKeyCredentialSource.php#L190 it checks if the instance have all the keys but `PublicKeyCredentialSource` created by older version doesn't contain `otherUI`, which breaks the backward compatibility.

If `otherUI` is necessary, I think I can update my own application's code instead of this library.

**Comment by Spomky** [comment]
Hi,

This should be fixed with `v3.3.7` (my mistake, I missed deploying this tag).
`otherUI` is introduced by the new [Webauthn Level 2 spec](https://www.w3.org/TR/webauthn-2/#public-key-credential-source-otherui)

**Comment by yrccondor** [comment]
Hi,

unfortunately it still doesn't work.

https://github.com/web-auth/webauthn-framework/blob/6109cbe179ec94b8fe155226b4c4e943b2c5159e/src/webauthn/src/PublicKeyCredentialSource.php#L188 will return a array with integer keys so https://github.com/web-auth/webauthn-framework/blob/6109cbe179ec94b8fe155226b4c4e943b2c5159e/src/webauthn/src/PublicKeyCredentialSource.php#L189 doesn't work.

I made a quick fix for this 

```php
if (($key = array_search('otherUI', $keys)) !== false) {
    unset($keys[$key]);
}
```

it works fine, so it's the only problem now.

**Comment by Spomky** [comment]
Correct. I've patch the method and added tests to make sure BC is ensured.
Should be fine now (`v3.3.8`).

**Comment by yrccondor** [comment]
cool, I confirm everything is working now. Thanks for your awesome work!
